services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  producer-service:
    build:
      context: ./producer-service
    depends_on:
      - rabbitmq
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
      RABBITMQ_QUEUE: telegram.notifications

  consumer-service:
    build:
      context: ./consumer-service
    depends_on:
      - rabbitmq
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
      RABBITMQ_QUEUE: telegram.notifications
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
